## Created by: Austin Larsen -- UVU Sysadmin II -- Testing Purposes Only ## 
## Install Nginx PlayBook ## 
---
- name: Install nginx
  hosts: localhost
  become: true

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present
       

  - name: Install nginx
    yum:
      name: nginx
      state: present
   

  #- name: Insert Default Index Page
  #  template:
  #    src: /etc/ansible/sources/index.html
  #    dest: /usr/share/nginx/html/index.html

  - name: copy the nginx default config file
    copy:
      src: /etc/ansible/sources/nginx.basic
      dest: /etc/nginx/sites-available/default.cfg
   

  - name: Start NGiNX
    service:
      name: nginx
      state: started
