## Install Nginx # 

- name: nginx-basic
  hosts: all
  tasks:
- name: install the latest version of nginx
  yum:
    name: nginx
    state: latest
- name: start nginx 
  name: nginx
  state: started 
  
  ## Configure Nginx ## 
  # - name: copy the nginx config file and restart nginx
  #   copy:
  #     src: /etc/ansible/sources/nginx.basic
  #      dest: /etc/nginx/sites-available/test-site.cfg
  #   become: yes
  #  - name: create symlink
  #    file:
  #      src: /etc/nginx/sites-available/test-site.cfg
  #      dest: /etc/nginx/sites-enabled/default
  #      state: link
       
       
  ## Restart Nginx ## 
  - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes

